version: '3'
services:
  label-studio:
    image: heartexlabs/label-studio:latest
    ports:
      - "8200:8200"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/media
    volumes:
      - ./data:/label-studio/data
      - ../downloaded_images:/label-studio/media:ro
